// Generated by CoffeeScript 1.7.1
$(function() {
  var RANK, TIME, addRecord, areaHeight, areaSize, areaWidth, changeLevel, changeQuizCount, colorBackArr, colorQuiz, colorTextArr, countDown, countStart, exitGame, initGame, initGameView, initQuiz, judgeAnswer, newRecord, quizCount, quizLevel, recordStorage, reportScore, selectRank, showLeaderboard, stageCount, time, timeChangeMinus, timeChangePlus, timeFont, timer;
  colorBackArr = ['#000000', 'white', '#DD0000', '#FFFF77', '#00FF00', '#0000FF', '#FF44FF', '#FF6928'];
  colorTextArr = ['黒', '白', '赤', '黄', '緑', '青', '紫', '橙'];
  colorQuiz = [];
  TIME = 60;
  time = TIME;
  timer = null;
  areaWidth = screen.width;
  areaHeight = screen.height - (20 + 50 + 13);
  areaSize = areaWidth + areaHeight;
  $('.touch_area').css({
    'width': areaWidth,
    'height': areaHeight
  });
  quizLevel = 1;
  stageCount = 0;
  quizCount = 0;
  RANK = 7;
  initGame = function() {
    quizLevel = 1;
    stageCount = 0;
    quizCount = 0;
    time = TIME;
    return initGameView();
  };
  initGameView = function() {
    $('#header').css({
      'font-size': "" + (areaSize / 50) + "px"
    });
    $('.quiz_area').append($("<div id=\"quiz_0\"class=\"quiz_color\"></div>"));
    $('.quiz_color').css({
      'width': '100%',
      'height': '100%',
      'font-size': "" + (areaSize / 5) + "px"
    });
    initQuiz();
    return countStart();
  };
  initQuiz = function() {
    var colorBackCount, colorTextCount, i, randomBack, randomText, _i, _results;
    stageCount++;
    quizCount = 0;
    $('#stage_count').text(stageCount);
    colorQuiz.length = 0;
    changeLevel();
    $('.quiz_color').css({
      'opacity': '1.0'
    });
    colorBackCount = colorBackArr.length - 1;
    colorTextCount = colorTextArr.length - 1;
    _results = [];
    for (i = _i = 0; 0 <= quizLevel ? _i < quizLevel : _i > quizLevel; i = 0 <= quizLevel ? ++_i : --_i) {
      randomBack = _.random(colorBackCount);
      randomText = _.random(colorTextCount);
      colorQuiz.push(randomText);
      _results.push($("#quiz_" + i).css({
        'color': colorBackArr[randomBack]
      }).text(colorTextArr[randomText]));
    }
    return _results;
  };
  newRecord = localStorage.getItem('record2');
  recordStorage = function() {
    var record2;
    record2 = localStorage.getItem('record2');
    if (stageCount > record2) {
      localStorage.setItem('record2', stageCount);
      newRecord = localStorage.getItem('record2');
      return reportScore();
    }
  };
  addRecord = function() {
    var yourRank;
    yourRank = Math.round(newRecord / RANK + 0.01);
    if (newRecord) {
      return $('#record .count').text("" + rankArray[yourRank] + " ");
    }
  };
  judgeAnswer = function(value) {
    var colorId, quizValue;
    colorId = Number(value.slice(6));
    quizValue = colorQuiz[quizCount];
    if (colorId === quizValue) {
      $("#quiz_" + quizCount).animate({
        opacity: '0'
      }, 200);
      quizCount++;
      if (quizCount === quizLevel) {
        time += 3;
        timeFont();
        timeChangePlus();
        return setTimeout(function() {
          return initQuiz();
        }, 300);
      }
    } else {
      time -= 3;
      if (time < 1) {
        time = 0;
        $('#time_count').css('color', 'black').text(time);
        exitGame();
      }
      $('#overlay_false').show().fadeOut(50);
      timeFont();
      return timeChangeMinus();
    }
  };
  changeLevel = function() {
    switch (stageCount) {
      case 5:
        quizLevel = 2;
        changeQuizCount(quizLevel);
        return $('.quiz_color').css({
          'width': '50%',
          'height': '100%',
          'font-size': "" + (areaSize / 5) + "px"
        });
      case 10:
        quizLevel = 4;
        changeQuizCount(quizLevel);
        return $('.quiz_color').css({
          'width': '50%',
          'height': '50%',
          'font-size': "" + (areaSize / 8) + "px"
        });
      case 15:
        quizLevel = 9;
        changeQuizCount(quizLevel);
        return $('.quiz_color').css({
          'width': '33.333%',
          'height': '33.333%',
          'font-size': "" + (areaSize / 12.5) + "px"
        });
    }
  };
  changeQuizCount = function(value) {
    var i, _i, _results;
    $('.quiz_area').empty();
    _results = [];
    for (i = _i = 0; 0 <= value ? _i < value : _i > value; i = 0 <= value ? ++_i : --_i) {
      _results.push($('.quiz_area').append($("<div id=\"quiz_" + i + "\"class=\"quiz_color\"></div>")));
    }
    return _results;
  };
  $('.select_color').bind('touchstart', function() {
    return $(this).addClass('touch_active');
  });
  $('.select_color').bind('touchend', function() {
    var selectColor;
    $(this).removeClass('touch_active');
    selectColor = $(this).attr('id');
    return judgeAnswer(selectColor);
  });
  countStart = function() {
    return timer = setInterval(countDown, 1000);
  };
  countDown = function() {
    time--;
    timeFont();
    if (time < 1) {
      time = 0;
      $('#time_count').css('color', 'black').text(time);
      return exitGame();
    }
  };
  timeFont = function() {
    if (time <= 10) {
      $('#time_count').css('color', 'red').text(time);
    } else {
      $('#time_count').css('color', 'black').text(time);
    }
    return $('#time_count').text(time);
  };
  timeChangePlus = function() {
    $('#time_change').text('+3');
    $('#time_change').css({
      'display': 'inline',
      'color': 'blue'
    });
    return setTimeout(function() {
      $('#time_change').addClass('correct');
      return setTimeout(function() {
        $('#time_change').removeClass('correct');
        return setTimeout(function() {
          return $('#time_change').css('display', 'none');
        }, 1);
      }, 200);
    }, 100);
  };
  timeChangeMinus = function() {
    $('#time_change').text('-3');
    $('#time_change').css({
      'display': 'inline',
      'color': 'red'
    });
    return setTimeout(function() {
      $('#time_change').addClass('wrong');
      return setTimeout(function() {
        $('#time_change').removeClass('wrong');
        return setTimeout(function() {
          return $('#time_change').css('display', 'none');
        }, 1);
      }, 200);
    }, 100);
  };
  exitGame = function() {
    clearInterval(timer);
    $('#overlay_close').show();
    return recordStorage();
  };
  selectRank = function() {
    var i;
    i = 0;
    while (i * RANK < stageCount) {
      i++;
    }
    return $('#change_text_end').text(rankArray[i]);
  };
  showLeaderboard = function() {
    return GameCenter.prototype.showLeaderboard('iroiroyayakoshize_rank');
  };
  reportScore = function() {
    GameCenter.prototype.reportScore('iroiroyayakoshize_rank', newRecord);
    return setTimeout('showLeaderboard()', 2000);
  };
  addRecord();
  $('#start').bind('touchend', function() {
    $('#container_start').fadeOut('fast');
    $('#container_game').delay(400).fadeIn('slow');
    return initGame();
  });
  $('#ranking').bind('touchend', function() {
    return showLeaderboard();
  });
  $('#overlay_close #close_1').bind('touchend', function() {
    selectRank();
    addRecord();
    $('#countQuestion .count').text(stageCount);
    $('#overlay_close').fadeOut('slow');
    $('#container_game').fadeOut('fast');
    $('#overlay_rank').delay(300).fadeIn('slow');
    return $('#container_end').delay(400).fadeIn('slow');
  });
  $('#overlay_rank #close_2').bind('touchend', function() {
    return $('#overlay_rank').fadeOut('normal');
  });
  $('#restart').bind('touchend', function() {
    $('#overlay_advertisement').show();
    $('#container_end').fadeOut('fast');
    return $('#container_start').delay(400).fadeIn('slow');
  });
  return $('#overlay_advertisement #close_3').bind('touchend', function() {
    return $('#overlay_advertisement').fadeOut('slow');
  });
});
